MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/VGG/VGG-16"
  ROI_BOX_HEAD:
    FEATURE_EXTRACTOR: "VGG16Conv5ROIFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    MLP_HEAD_DIM: 4096
    NUM_CLASSES: 21
  BACKBONE:
    CONV_BODY: VGG-16
  RESNETS:
    BACKBONE_OUT_CHANNELS: 512
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 300
    ANCHOR_SIZES: (128, 256, 512)

DATASETS:
  TRAIN: ("voc_2007_train", "voc_2007_val")
  TEST: ("voc_2007_test",)
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0005
  STEPS: (50000, )
  MAX_ITER: 70000
  IMS_PER_BATCH: 1
TEST:
  IMS_PER_BATCH: 1
